{% set version = "0.8.1" %}

package:
  name: toolz
  version: {{ version }}

source:
  fn: toolz-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/toolz/toolz-{{ version }}.tar.gz
  md5: f3b60d62bd3906fe1881b748c9ee82a1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools
    - python

  run:
    - python

test:
  imports:
    - toolz
    - toolz.curried
    - toolz.sandbox

about:
  home: http://toolz.readthedocs.org/
  license: BSD 3-Clause
  summary: A functional standard library for Python.

extra:
  recipe-maintainers:
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
