{% set version = "0.11.0" %}

package:
  name: toolz
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/toolz/toolz-{{ version }}.tar.gz
  sha256: 39701a4c1ed9498e9d4847bb52181807b9f90c598ee9dd5ed27b0f4c007a595a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox

about:
  home: http://toolz.readthedocs.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A functional standard library for Python

extra:
  recipe-maintainers:
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
    - ocefpaf
