{% set version = "0.11.2" %}

package:
  name: toolz
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/toolz/toolz-{{ version }}.tar.gz
  sha256: 6b312d5e15138552f1bda8a4e66c30e236c831b612b2bf0005f8a1df10a4bc33

build:
  number: 0
  skip: True  # [py<35]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.5

test:
  imports:
    - tlz
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox
  requires:
    - pip
    - python <3.10
    - pytest
  commands:
    - pip check
    - pytest -x --doctest-modules --pyargs toolz

about:
  home: http://toolz.readthedocs.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: List processing tools and functional utilities
  description: |
    Toolz provides a set of utility functions for iterators, functions, and
    dictionaries. These functions interoperate well and form the building
    blocks of common data analytic operations. They extend the standard
    libraries itertools and functools and borrow heavily from the standard
    libraries of contemporary functional languages.
  doc_url: http://toolz.readthedocs.org/en/latest/
  doc_source_url: https://github.com/pytoolz/toolz/blob/master/doc/source/index.rst
  dev_url: https://github.com/pytoolz/toolz

extra:
  recipe-maintainers:
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
    - ocefpaf
