{% set version = "0.8.1" %}

package:
  name: toolz
  version: {{ version }}

source:
  fn: toolz-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/toolz/toolz-{{ version }}.tar.gz
  sha256: b3922e3545e892b4aeac5c20ea19fef75b3dfe366f1f2fcea941b3c836b3c160

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools
    - python

  run:
    - python

test:
  imports:
    - toolz
    - toolz.curried
    - toolz.sandbox

about:
  home: http://toolz.readthedocs.org/
  license: BSD 3-Clause
  summary: A functional standard library for Python.

extra:
  recipe-maintainers:
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
