{% set name = "toolz" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toolz-{{ version }}.tar.gz
  sha256: 27a5c770d068c110d9ed9323f24f1543e83b2f300a687b7891c1a6d56b697b5b

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=77
    - setuptools-git-versioning >=2.0
  run:
    - python

test:
  imports:
    - tlz
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "import toolz; assert toolz.__version__ != '0.0.0'"
    - pytest --doctest-modules --pyargs toolz

about:
  home: https://github.com/pytoolz/toolz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: List processing tools and functional utilities
  description: |
    Toolz provides a set of utility functions for iterators, functions, and
    dictionaries. These functions interoperate well and form the building
    blocks of common data analytic operations. They extend the standard
    libraries itertools and functools and borrow heavily from the standard
    libraries of contemporary functional languages.
  doc_url: https://toolz.readthedocs.io/
  dev_url: https://github.com/pytoolz/toolz

extra:
  recipe-maintainers:
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
    - ocefpaf
