travis:
  secure:
    BINSTAR_TOKEN: abBmWJdLhaFqrrjvNMFzkNoxKfRK6MRDteFeG5b5pxyLgArxOrWdnSgFdID5B4qIbp/luURhTjrCil+rdryeuDBETa7ILOj63mC4BduPTQ+9XYOYxCuiSyv47xKEEmRzITDYRCoXaAPq6Y7nhKiDN9XZA/J1FsQBq51vMMiqkAmAbxr45RECxjcNvZ0Jzq0GETVVH1+5GgFd+v/W4pXgdY1SX38yEvfFORVyZBAmMWGKaYF3FzTS/HXvL3Ogp3XSszLpCvMLZJ5V/lahu5iBMwU7BL9vRpOHWQgO42ZCQoPoxNHazwENWpcGkQ15/jJYH/IW2+oLYctDT4TUHL9dkQviV7uU7lqeD2TtTdA5TxyNZG3444e45TQ1sf7P1r5xdvEs7KeuL1/QvO6c8jys6KmTe0SkrTJAUHJ6JsRaloewzrNxBkgX9tRGotGKd7nunQ3gn+ye3eOOdMG8R3mdsu8JWKbCs+wYLeGkrVRjonMsJNi5LeeZMns8MbcgtTF/od4aDWiaK5BtT/Ph5xwwpzroHRiYc+Pr+uN89hN3nNlzupsRvCcjJ5u85uFO0QUFZBcUYSqAyuKur9bc3q4x+GLQ4ky6vR8cPaESE3Qk5qlH6ddbUldGVXS3vIHXPrxH0mRSV4BKWsCXFQIVQjjTctHW2fV5Y3q9+DLKPU8+cR8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
