travis:
  secure:
    BINSTAR_TOKEN: Q2z8fROyYbnujwGrCQpv4mhGZSgsGf6GrMoZoMF/hWI2NZaY3zKbeautMdR7FTCWn+HipNx/G/XqjSL8YlSWcI6RcGPVHAEu9u5M7FgvpM5t5d/9hCed5BJRWqjzAM+Yc2M9RxglOAAdljqqztHHXUKcfNgskNNQHMLenpbc5AmYU6b5xx17JMAo10EfyLyub4qs0nupIpeJUG19CqChRp4k8sJZD/oACJtqYj9+WieH3ZggGeka0CuYLKNpJenNGzg8aHq6jIrjwhiOL0aElTToZmBw6oGYJLoLUxJ2Gf1KNWcShie4IeYBtp6nM3FByPerGeF19AYoeoTpBIb/UiCl2TSvksIwUpNuJ0r/4gfNLFzYbU3dJ3osDo3sVmHzTvLUiJpmHBYYAXS28zqV6UGqUcN7+8O8XbFaGelq6LeFLhmZqtbdr24nfi2SNiw+teClD+dqnDctQoKyW4HhJYDo5Yf0WWNykmgXgZTFzC6Nh1wdo3BDZCFFp93ab6xyHsV70/e0M9O/zs+qbpt0mnHL6OP7hHZqZzolxt/2y4Jd/uUcP6SfP4wOTCGCb9q1N/nnh1ORTiND5yd18Er/pI9jcADMqg8FlO7X7ITmW+/p34tUCTf36U6t5VPmlWDt2EqFLaPZCmsj9FknmW9LvI1DmU2UBFdnJjRCGzIYZNA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
